// flow-typed signature: 14ca438aa0c11e88a83dfe45bccb05d0
// flow-typed version: <<STUB>>/is-fullwidth-code-point_v^2.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-fullwidth-code-point'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-fullwidth-code-point' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-fullwidth-code-point/index' {
  declare module.exports: $Exports<'is-fullwidth-code-point'>;
}
declare module 'is-fullwidth-code-point/index.js' {
  declare module.exports: $Exports<'is-fullwidth-code-point'>;
}
