// flow-typed signature: 28a7cc760bcb7f575133019cc0cd2876
// flow-typed version: <<STUB>>/jest-runner-flowtype_v^0.0.5/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-runner-flowtype'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-runner-flowtype' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-runner-flowtype/src/FlowtypeRunner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-runner-flowtype/index' {
  declare module.exports: $Exports<'jest-runner-flowtype'>;
}
declare module 'jest-runner-flowtype/index.js' {
  declare module.exports: $Exports<'jest-runner-flowtype'>;
}
declare module 'jest-runner-flowtype/src/FlowtypeRunner.js' {
  declare module.exports: $Exports<'jest-runner-flowtype/src/FlowtypeRunner'>;
}
