// flow-typed signature: 670a68200c163a18b685400fa99d8d44
// flow-typed version: <<STUB>>/wcwidth_v^1.0.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wcwidth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wcwidth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wcwidth/combining' {
  declare module.exports: any;
}

declare module 'wcwidth/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wcwidth/combining.js' {
  declare module.exports: $Exports<'wcwidth/combining'>;
}
declare module 'wcwidth/index' {
  declare module.exports: $Exports<'wcwidth'>;
}
declare module 'wcwidth/index.js' {
  declare module.exports: $Exports<'wcwidth'>;
}
declare module 'wcwidth/test/index.js' {
  declare module.exports: $Exports<'wcwidth/test/index'>;
}
