// flow-typed signature: 2ed258db46ad21093b92ddf98a2c8cbb
// flow-typed version: <<STUB>>/wrap-ansi_v^4.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wrap-ansi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wrap-ansi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'wrap-ansi/index' {
  declare module.exports: $Exports<'wrap-ansi'>;
}
declare module 'wrap-ansi/index.js' {
  declare module.exports: $Exports<'wrap-ansi'>;
}
